#---
#- hosts: ora
#  user: root
#  gather_facts: no
#  vars_prompt:
#    - name: hostname
#      prompt: "Please input a FQDN hostname: "
#      private: no
#Prepare host for oracle installation
#  tasks:
- name: Fully update
  yum:
    name: '*'
    state: latest

- name: Update kernel and verify it latest statement
  yum:
    name: kernel-*
    state: latest

- name: Set timezone to Asia/Yekaterinburg
  timezone:
    name: Asia/Yekaterinburg

- name: Add groups for database managment
  group: 
    gid: "{{ item.gid  }}" 
    name: "{{ item.name }}"
  with_items:
    - { gid: '54321', name: 'oinstall'}
    - { gid: '54322', name: 'dba'}
    - { gid: '54323', name: 'oper'}
    - { gid: '54324', name: 'backupdba'}
    - { gid: '54325', name: 'dgdba'}
    - { gid: '54326', name: 'kmdba'}
    - { gid: '54327', name: 'asmdba'}
    - { gid: '54328', name: 'asmoper'}
    - { gid: '54329', name: 'asmadmin'}
    - { gid: '54330', name: 'racdba'}
  tags:
    - groups
    
- name: Add user Oracle
  user:
    uid: 54321
    name: oracle
    group: oinstall
    groups: "{{ item }}"
    append: yes
  with_items:
    - dba
    - oper
    - backupdba
    - dgdba
    - kmdba
    - racdba
   
#- Set user Oracle password

- name: Install requiered packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - compat-libcap1
    - compat-libstdc++-33
    - glibc
    - glibc-devel
    - ksh
    - libaio
    - libaio-devel
    - libX11
    - libXau
    - libXi
    - libXtst
    - libgcc
    - libstdc++
    - libstdc++-devel
    - libxcb
    - make 
    - nfs-utils
    - smartmontools
    - net-tools
    - sysstat 
    - tmux
    - openssh-server
    - tree
    - mc
    - xclock
    - xauth
    - xorg-x11-utils

- name: Add kernel parameters
  blockinfile:
    dest: /etc/sysctl.conf
    block: |
      fs.file-max = 6815744
      kernel.sem = 250 32000 100 128
      kernel.shmmni = 4096
      kernel.shmall = 1073741824
      kernel.shmmax = 4398046511104
      net.core.rmem_default = 262144
      net.core.rmem_max = 4194304
      net.core.wmem_default = 262144
      net.core.wmem_max = 1048576
      fs.aio-max-nr = 1048576
      net.ipv4.ip_local_port_range = 9000 65500
      kernel.panic_on_oops=1
    backup: yes
  tags: sysctl

- name: Apply kernel parameters
  shell: "/sbin/sysctl -p"
  tags: sysctl

- name: Set shell limits for user oracle in file /etc/security/limits.conf
  blockinfile:
    dest: /etc/security/limits.conf
    block: |
      # shell limits for users oracle 12gR2

      oracle   soft   nofile   1024
      oracle   hard   nofile   65536
      oracle   soft   nproc    2047
      oracle   hard   nproc    16384
      oracle   soft   stack    10240
      oracle   hard   stack    32768
      oracle   soft   memlock  3145728
      oracle   hard   memlock  3145728
    backup: yes
  tags: limits

- name: Check and disable Firewalld
  service: 
    name: firewalld.service
    state: stopped
    enabled: False
  tags: firewall
 
- name: Check and disable SELinux
  selinux:
    state: disabled

- name: Modify .bash_profile for user Oracle
  copy:
    src: bash_profile
    dest: /home/oracle/.bash_profile
    owner: oracle
    group: oinstall
    backup: yes
  tags: profile
  
- name: Create directory structure for Oracle DB
  file:
    path: /ora01/app/oracle/product/12.2.0/db_1
    state: directory
    owner: oracle
    group: oinstall
  tags: dir
# - name: Start ssh server with X forwarding
 
